# Single-AZ PostgreSQL instance in private subnets only, reachable solely
# from the existing ECS tasks security group. The master password is
# generated by Terraform and never appears in state as a plain output —
# it is stored only in the Secrets Manager secret this module creates.
#
# Service-owned schemas and least-privilege application DB roles are NOT
# provisioned here: that is handled at the application/database migration
# layer (e.g. Flyway/Prisma/alembic migrations run by each service),
# consistent with the sale-payment contract's ownership boundaries.

resource "random_password" "master" {
  length  = 24
  special = true
  # Exclude characters RDS rejects in passwords: "/", "@", '"', and space.
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-postgres-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = var.tags
}

resource "aws_security_group" "rds" {
  name        = "${var.name_prefix}-rds-sg"
  description = "PostgreSQL: ingress only from the ECS tasks security group"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, {
    Name = "${var.name_prefix}-rds-sg"
  })
}

resource "aws_security_group_rule" "rds_ingress_from_ecs" {
  type                     = "ingress"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = var.ecs_tasks_security_group_id
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  description              = "ECS tasks to PostgreSQL"
}

resource "aws_security_group_rule" "rds_egress_all" {
  type              = "egress"
  security_group_id = aws_security_group.rds.id
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false
  multi_az               = false

  backup_retention_period = var.backup_retention_period
  deletion_protection     = var.deletion_protection
  skip_final_snapshot     = var.skip_final_snapshot

  auto_minor_version_upgrade = true

  tags = var.tags
}

resource "aws_secretsmanager_secret" "db" {
  name        = "${var.name_prefix}-rds-postgres-credentials"
  description = "Generated master credentials + connection info for ${var.name_prefix}-postgres. Never committed to source."

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
    username = var.master_username
    password = random_password.master.result
  })
}

# Scoped, read-only access for the shared ECS task role to fetch DB
# credentials at runtime. Additive only — does not modify the role itself.
data "aws_iam_policy_document" "task_read_secret" {
  statement {
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [aws_secretsmanager_secret.db.arn]
  }
}

resource "aws_iam_role_policy" "task_read_db_secret" {
  name   = "${var.name_prefix}-ecs-task-read-db-secret"
  role   = var.ecs_task_role_name
  policy = data.aws_iam_policy_document.task_read_secret.json
}
